// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/opencontainers/go-digest"
	"github.com/opencontainers/image-spec/specs-go/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMultipart creates a new instance of MockMultipart. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMultipart(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMultipart {
	mock := &MockMultipart{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMultipart is an autogenerated mock type for the Multipart type
type MockMultipart struct {
	mock.Mock
}

type MockMultipart_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMultipart) EXPECT() *MockMultipart_Expecter {
	return &MockMultipart_Expecter{mock: &_m.Mock}
}

// PullTo provides a mock function for the type MockMultipart
func (_mock *MockMultipart) PullTo(ctx context.Context, repo string, dgst digest.Digest, path string) error {
	ret := _mock.Called(ctx, repo, dgst, path)

	if len(ret) == 0 {
		panic("no return value specified for PullTo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, digest.Digest, string) error); ok {
		r0 = returnFunc(ctx, repo, dgst, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMultipart_PullTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullTo'
type MockMultipart_PullTo_Call struct {
	*mock.Call
}

// PullTo is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - dgst digest.Digest
//   - path string
func (_e *MockMultipart_Expecter) PullTo(ctx any, repo any, dgst any, path any) *MockMultipart_PullTo_Call {
	return &MockMultipart_PullTo_Call{Call: _e.mock.On("PullTo", ctx, repo, dgst, path)}
}

func (_c *MockMultipart_PullTo_Call) Run(run func(ctx context.Context, repo string, dgst digest.Digest, path string)) *MockMultipart_PullTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 digest.Digest
		if args[2] != nil {
			arg2 = args[2].(digest.Digest)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMultipart_PullTo_Call) Return(err error) *MockMultipart_PullTo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMultipart_PullTo_Call) RunAndReturn(run func(ctx context.Context, repo string, dgst digest.Digest, path string) error) *MockMultipart_PullTo_Call {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function for the type MockMultipart
func (_mock *MockMultipart) Push(ctx context.Context, repo string, path string, partSize int64) (v1.Descriptor, error) {
	ret := _mock.Called(ctx, repo, path, partSize)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 v1.Descriptor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) (v1.Descriptor, error)); ok {
		return returnFunc(ctx, repo, path, partSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) v1.Descriptor); ok {
		r0 = returnFunc(ctx, repo, path, partSize)
	} else {
		r0 = ret.Get(0).(v1.Descriptor)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = returnFunc(ctx, repo, path, partSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMultipart_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockMultipart_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - path string
//   - partSize int64
func (_e *MockMultipart_Expecter) Push(ctx any, repo any, path any, partSize any) *MockMultipart_Push_Call {
	return &MockMultipart_Push_Call{Call: _e.mock.On("Push", ctx, repo, path, partSize)}
}

func (_c *MockMultipart_Push_Call) Run(run func(ctx context.Context, repo string, path string, partSize int64)) *MockMultipart_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMultipart_Push_Call) Return(descriptor v1.Descriptor, err error) *MockMultipart_Push_Call {
	_c.Call.Return(descriptor, err)
	return _c
}

func (_c *MockMultipart_Push_Call) RunAndReturn(run func(ctx context.Context, repo string, path string, partSize int64) (v1.Descriptor, error)) *MockMultipart_Push_Call {
	_c.Call.Return(run)
	return _c
}
