// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/opencontainers/go-digest"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBlobs creates a new instance of MockBlobs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlobs(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlobs {
	mock := &MockBlobs{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlobs is an autogenerated mock type for the Blobs type
type MockBlobs struct {
	mock.Mock
}

type MockBlobs_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlobs) EXPECT() *MockBlobs_Expecter {
	return &MockBlobs_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function for the type MockBlobs
func (_mock *MockBlobs) Exists(ctx context.Context, dgst digest.Digest) (bool, error) {
	ret := _mock.Called(ctx, dgst)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, digest.Digest) (bool, error)); ok {
		return returnFunc(ctx, dgst)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, digest.Digest) bool); ok {
		r0 = returnFunc(ctx, dgst)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, digest.Digest) error); ok {
		r1 = returnFunc(ctx, dgst)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlobs_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockBlobs_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - dgst digest.Digest
func (_e *MockBlobs_Expecter) Exists(ctx any, dgst any) *MockBlobs_Exists_Call {
	return &MockBlobs_Exists_Call{Call: _e.mock.On("Exists", ctx, dgst)}
}

func (_c *MockBlobs_Exists_Call) Run(run func(ctx context.Context, dgst digest.Digest)) *MockBlobs_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 digest.Digest
		if args[1] != nil {
			arg1 = args[1].(digest.Digest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlobs_Exists_Call) Return(b bool, err error) *MockBlobs_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBlobs_Exists_Call) RunAndReturn(run func(ctx context.Context, dgst digest.Digest) (bool, error)) *MockBlobs_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Pull provides a mock function for the type MockBlobs
func (_mock *MockBlobs) Pull(ctx context.Context, dgst digest.Digest) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, dgst)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, digest.Digest) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, dgst)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, digest.Digest) io.ReadCloser); ok {
		r0 = returnFunc(ctx, dgst)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, digest.Digest) error); ok {
		r1 = returnFunc(ctx, dgst)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlobs_Pull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pull'
type MockBlobs_Pull_Call struct {
	*mock.Call
}

// Pull is a helper method to define mock.On call
//   - ctx context.Context
//   - dgst digest.Digest
func (_e *MockBlobs_Expecter) Pull(ctx any, dgst any) *MockBlobs_Pull_Call {
	return &MockBlobs_Pull_Call{Call: _e.mock.On("Pull", ctx, dgst)}
}

func (_c *MockBlobs_Pull_Call) Run(run func(ctx context.Context, dgst digest.Digest)) *MockBlobs_Pull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 digest.Digest
		if args[1] != nil {
			arg1 = args[1].(digest.Digest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlobs_Pull_Call) Return(readCloser io.ReadCloser, err error) *MockBlobs_Pull_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockBlobs_Pull_Call) RunAndReturn(run func(ctx context.Context, dgst digest.Digest) (io.ReadCloser, error)) *MockBlobs_Pull_Call {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function for the type MockBlobs
func (_mock *MockBlobs) Push(ctx context.Context, dgst digest.Digest, size int64, r io.Reader) error {
	ret := _mock.Called(ctx, dgst, size, r)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, digest.Digest, int64, io.Reader) error); ok {
		r0 = returnFunc(ctx, dgst, size, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlobs_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockBlobs_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - ctx context.Context
//   - dgst digest.Digest
//   - size int64
//   - r io.Reader
func (_e *MockBlobs_Expecter) Push(ctx any, dgst any, size any, r any) *MockBlobs_Push_Call {
	return &MockBlobs_Push_Call{Call: _e.mock.On("Push", ctx, dgst, size, r)}
}

func (_c *MockBlobs_Push_Call) Run(run func(ctx context.Context, dgst digest.Digest, size int64, r io.Reader)) *MockBlobs_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 digest.Digest
		if args[1] != nil {
			arg1 = args[1].(digest.Digest)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBlobs_Push_Call) Return(err error) *MockBlobs_Push_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlobs_Push_Call) RunAndReturn(run func(ctx context.Context, dgst digest.Digest, size int64, r io.Reader) error) *MockBlobs_Push_Call {
	_c.Call.Return(run)
	return _c
}
