// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockManifests creates a new instance of MockManifests. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManifests(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManifests {
	mock := &MockManifests{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManifests is an autogenerated mock type for the Manifests type
type MockManifests struct {
	mock.Mock
}

type MockManifests_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManifests) EXPECT() *MockManifests_Expecter {
	return &MockManifests_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockManifests
func (_mock *MockManifests) Get(ctx context.Context, ref string, accept string) ([]byte, string, error) {
	ret := _mock.Called(ctx, ref, accept)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]byte, string, error)); ok {
		return returnFunc(ctx, ref, accept)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []byte); ok {
		r0 = returnFunc(ctx, ref, accept)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = returnFunc(ctx, ref, accept)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, ref, accept)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockManifests_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockManifests_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
//   - accept string
func (_e *MockManifests_Expecter) Get(ctx any, ref any, accept any) *MockManifests_Get_Call {
	return &MockManifests_Get_Call{Call: _e.mock.On("Get", ctx, ref, accept)}
}

func (_c *MockManifests_Get_Call) Run(run func(ctx context.Context, ref string, accept string)) *MockManifests_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManifests_Get_Call) Return(raw []byte, contentType string, err error) *MockManifests_Get_Call {
	_c.Call.Return(raw, contentType, err)
	return _c
}

func (_c *MockManifests_Get_Call) RunAndReturn(run func(ctx context.Context, ref string, accept string) ([]byte, string, error)) *MockManifests_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockManifests
func (_mock *MockManifests) Put(ctx context.Context, ref string, mediaType string, raw []byte) error {
	ret := _mock.Called(ctx, ref, mediaType, raw)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte) error); ok {
		r0 = returnFunc(ctx, ref, mediaType, raw)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManifests_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockManifests_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
//   - mediaType string
//   - raw []byte
func (_e *MockManifests_Expecter) Put(ctx any, ref any, mediaType any, raw any) *MockManifests_Put_Call {
	return &MockManifests_Put_Call{Call: _e.mock.On("Put", ctx, ref, mediaType, raw)}
}

func (_c *MockManifests_Put_Call) Run(run func(ctx context.Context, ref string, mediaType string, raw []byte)) *MockManifests_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockManifests_Put_Call) Return(err error) *MockManifests_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManifests_Put_Call) RunAndReturn(run func(ctx context.Context, ref string, mediaType string, raw []byte) error) *MockManifests_Put_Call {
	_c.Call.Return(run)
	return _c
}
